import Head from 'next/head'
import Image from 'next/image'
import { Ubuntu } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Script from 'next/script'
import { Suspense } from 'react'
import Loading from '@/components/Loading'

const ubuntu = Ubuntu({ subsets: ['latin'], weight: '300' })

export function getServerSideProps() {
  return {
    props: {
      title: "Section Home"
    }
  }
}

export default function Home(props) {
  const { title } = props;
  const menu = [
    {
      title: 'Home',
      link: '/',
    },
    {
      title: 'About',
      link: '/about',
    },
    {
      title: 'Contact',
      link: '/contact',
    }
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <ul>
          {
            menu.map((item, i) => (
              <li key={i}><Link href={item.link}>{item.title}</Link></li>
            ))
          }
        </ul>

        <hr />

        <Suspense fallback={<Loading />}>
          <section className={ubuntu.className}>
            {title}

            <Image 
              width={100}
              height={100}
              alt='Ini Gambar'
              src={`/react.png`} 
              />
          </section>
        </Suspense>
      </main>
      <Script src="/js/main.js" />
    </>
  )
}
